# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’
use_frameworks!

target 'KIFTe' do

end

target 'KIFTeTests' do
  # pod 'KIF', :configurations => ['Debug']

end

target 'KIFTeUITests' do
  pod 'KIF'
  
end
