# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’
use_frameworks!

target 'KIFTarget' do

end

target 'Acceptance Tests' do
    pod 'KIF', :configurations => ['Debug']
  end


